python test.py --dataroot ../Self-inverse-master/datasets/brat_4imgs \
--checkpoints_dir /home/yifan/Github/One2one/checkpoints \
--name Brats_pix2pix_AtoB_self \
--direction AtoB \
--phase img1 \
--epoch 25 \
--model pix2pix --netG unet_256 \
--input_nc 1 \
--output_nc 1 \
--dataset_mode aligned \
--norm batch \