python test.py --dataroot ../Self-inverse-master/datasets/brat_4imgs \
--log_dir ../Self-inverse-master/logs/brat_4imglog/ \
--checkpoints_dir ./checkpoints \
--name BratsT1T2_pix2pix_AtoB \
--direction AtoB \
--phase img1 \
--epoch 25 \
--model pix2pix --netG unet_256 \
--input_nc 1 \
--output_nc 1 \
--dataset_mode aligned \
--norm batch \